twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    paths:
        '%kernel.project_dir%/templates/backend': backend
        '%kernel.project_dir%/templates/frontend': frontend
        '%kernel.project_dir%/templates/common': common
        '%kernel.project_dir%/templates/layout': layout
    date:
        format: d F Y
